version: '3.3'
services:

  anvil:
    ports:
      - '8545:8545'
    image: ghcr.io/foundry-rs/foundry:latest
    volumes:
      - ./genesis.json:/app/genesis.json
    entrypoint: anvil
    command: --init /app/genesis.json --accounts 0 --host 0.0.0.0

  w3-ctf:
    volumes:
      - ./.env:/app/.env
    ports:
      - '5555:5555'
    build: .
